#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path


def emit(text: str) -> None:
    print(text, flush=True)


def append_trace(kind: str, value: str = "") -> None:
    path = os.environ.get("FAKE_CODEX_TRACE_FILE")
    if not path:
        return
    with Path(path).open("a", encoding="utf-8") as handle:
        handle.write(f"{kind}:{value}\n")


def wait_for_line() -> str:
    line = sys.stdin.readline()
    if not line:
        time.sleep(0.05)
        return ""
    value = line.rstrip("\n")
    append_trace("stdin", value)
    return value


def ensure_git_identity() -> None:
    subprocess.run(["git", "config", "user.name", "Fake Codex"], check=True)
    subprocess.run(["git", "config", "user.email", "fake-codex@example.com"], check=True)


def make_commit() -> None:
    ensure_git_identity()
    Path("autogenerated.txt").write_text("fake codex commit\n", encoding="utf-8")
    subprocess.run(["git", "add", "autogenerated.txt"], check=True)
    subprocess.run(["git", "commit", "-m", "fake codex commit"], check=True)


def startup(delay: float) -> None:
    emit("Do you trust the contents of this directory?")
    while wait_for_line().strip() != "1":
        pass
    emit("Press Enter to continue")
    while wait_for_line().strip():
        pass
    time.sleep(delay)
    emit("model: gpt-5.4")
    emit("(esc to interrupt)")
    append_trace("ready", "shown")


def scenario_steady_complete(prompt: str) -> None:
    append_trace("prompt", prompt)
    emit("<< PHASE: IMPLEMENT >>")
    for idx in range(3):
        emit(f"progress {idx} (esc to interrupt)")
        time.sleep(0.15)
    emit("<< TASK COMPLETE >>")


def scenario_idle_then_complete(prompt: str) -> None:
    append_trace("prompt", prompt)
    emit("waiting for next step (esc to interrupt)")
    while True:
        line = wait_for_line()
        if line:
            emit("resumed after nudge")
            emit("<< TASK COMPLETE >>")
            return


def scenario_stalled_idle(prompt: str) -> None:
    append_trace("prompt", prompt)
    emit("stalled (esc to interrupt)")
    while True:
        wait_for_line()


def scenario_review_commit(prompt: str, make_real_commit: bool) -> None:
    append_trace("prompt", prompt)
    emit("<< PHASE: IMPLEMENT >>")
    emit("working (esc to interrupt)")
    time.sleep(0.1)
    emit("<< TASK COMPLETE >>")

    while "/review unstaged changes" not in wait_for_line():
        pass
    emit("<< Code review finished >>")

    while "Please fix all substantive issues" not in wait_for_line():
        pass
    emit("<< REVIEW FIXES COMPLETE >>")

    while "create the requested git commit" not in wait_for_line():
        pass
    if make_real_commit:
        make_commit()
    emit("<< COMMIT COMPLETE >>")


def scenario_commit_only(prompt: str, make_real_commit: bool) -> None:
    append_trace("prompt", prompt)
    emit("<< TASK COMPLETE >>")
    while "create the requested git commit" not in wait_for_line():
        pass
    if make_real_commit:
        make_commit()
    emit("<< COMMIT COMPLETE >>")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scenario", required=True)
    parser.add_argument("--startup-delay", type=float, default=0.05)
    parser.add_argument("--make-commit", action="store_true")
    args, _ = parser.parse_known_args()

    startup(args.startup_delay)

    prompt = ""
    while not prompt:
        prompt = wait_for_line().strip()

    if args.scenario == "steady-complete":
        scenario_steady_complete(prompt)
    elif args.scenario == "idle-then-complete":
        scenario_idle_then_complete(prompt)
    elif args.scenario == "stalled-idle":
        scenario_stalled_idle(prompt)
    elif args.scenario == "review-commit":
        scenario_review_commit(prompt, args.make_commit)
    elif args.scenario == "commit-only":
        scenario_commit_only(prompt, args.make_commit)
    else:
        raise SystemExit(f"unknown scenario: {args.scenario}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
